# Generated by Django 4.0.2 on 2022-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
    ]
