# Generated by Django 4.0.2 on 2022-04-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
