# Generated by Django 4.0.2 on 2022-04-12 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('doctor', models.CharField(choices=[('Aruzhan Askar', 'Aruzhan Askar'), ('Dosbol Bekgali', 'Dosbol Bekgali'), ('Nick Adel', 'Nick Adel'), ('Lucy Andro', 'Lucy Andro'), ('Aleksey Sergey', 'Aleksey Sergey'), ('Nikolas Spark', 'Nikolas Spark'), ('Samat Kozhagul', 'Samat Kozhagul'), ('Alma Serikkyzy', 'Alma Serikkyzy')], default='Doctor1', max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('app_date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Postponed', 'Postponed')], default='Not Completed', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('blood_pressure', models.IntegerField(default=0)),
                ('heart_beat', models.IntegerField(default=0)),
                ('haemoglobin', models.IntegerField(default=0)),
                ('sugar', models.IntegerField(default=0)),
                ('mod_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('speciality', models.CharField(choices=[('Pediatrician', 'Pediatrician'), ('Neurosurgeon', 'Neurosurgeon'), ('Radiologist', 'Radiologist'), ('Mammologist', 'Mammologist'), ('Dermatologist', 'Dermatologist'), ('Vascular Surgeon', 'Vascular Surgeon'), ('Ophthalmologist', 'Ophthalmologist'), ('Optometrist', 'Optometrist')], max_length=50, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('university', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('awards', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_management_system.category')),
            ],
        ),
    ]
