# Generated by Django 4.0.2 on 2022-05-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
